# Generated by Django 2.2.9 on 2020-08-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200823_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, error_messages={'Данный файл не является изображением. Попробуйте снова загрузить файл.': '1'}, help_text='Добавьте картинку к посту', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
